### ISSUE TITLE
Bug in zip_rename.py

### ISSUE THREAD

**Issue by Gretadelnista** [FrancescoLaruina/scripts#1]
You should add an extension to the create files, otherwise it unpacks them as .txt
I have resolved this bug in this way (line 29): 
file_.filename = '{}_{}.dcm'.format(prefix, idx)

**Comment by flaruina** [comment]
Actually they are not unpacked as text files but your computer is configured in such a way that it tries to interpret them as text: maybe the mime type association for image/dicom is not recognized.

As a check, please, try to open the files without extension directly with a viewer and let me know if it works.
Hardcoding ".dcm", would mean a loss of generality, I propose, instead, an additional option to specify an extension. Do you agree?

**Comment by Gretadelnista** [comment]
Yes, if the files are directly opened with a viewer it works.

**Comment by flaruina** [comment]
Ok, thanks for the check.
I added the option to chose an extension.
